package(default_visibility = ["//visibility:public"],)

cc_library(
    name = "math",
    hdrs = ["math.h"],
    # Using include_prefix does NOT work
    include_prefix = ".",
    # Using includes works
    # includes = ["."],
)
